"""
Django settings for webProject project.

Generated by 'django-admin startproject' using Django 2.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# print(BASE_DIR)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '-do5v*$o*sos7=yn@7!v64&jh(vc*&6ag1b7@s1lkj8g2=0un9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'dbModel',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'webProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR+"/templates",],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'webProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

#静态文件相关,参考：https://vra.github.io/django-template-generate.html
#http://blog.51cto.com/830909/1748958
#生产环境略有差别，无法使用
# 这个不生效
STATIC_URL = '/static/'
STATIC_DIRS=(
    os.path.join(BASE_DIR,'/static/')
)
# 这个不生效


# 这个生效
# 参考 https://blog.csdn.net/xxx_gt/article/details/79719790
MEDIA_URL = '/dbModel/templates/assets/'
MEDIA_ROOT = os.path.join(BASE_DIR,'dbModel/templates/assets')
# 这个生效

# print(STATIC_URL)
# print(BASE_DIR)
# SITE_ROOT = os.path.join(os.path.abspath(os.path.dirname(__file__)),'')
# STATIC_ROOT = os.path.join(SITE_ROOT,'assets')

# STATICFILES_DIRS = (
#     ("css", os.path.join(STATIC_ROOT,'css')),
#     ("js", os.path.join(STATIC_ROOT,'js')),
#     ("images", os.path.join(STATIC_ROOT,'images')),
#     ("libs",os.path.join(STATIC_ROOT,'libs')),
#     ("font",os.path.join(STATIC_ROOT,'font')),
#     ("fonts",os.path.join(STATIC_ROOT,'fonts')),
# )
