# Generated by Django 2.0.5 on 2018-06-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('host_id', models.IntegerField(max_length=10, null=True)),
                ('host_name', models.CharField(max_length=30, null=True)),
                ('ip_addr', models.CharField(max_length=16, null=True)),
                ('file_name', models.CharField(max_length=50, null=True)),
                ('file_type', models.CharField(default='file', max_length=10)),
                ('is_hide', models.IntegerField(default=0, max_length=1)),
                ('time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proc',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('host_id', models.IntegerField(max_length=10, null=True)),
                ('host_name', models.CharField(max_length=30, null=True)),
                ('ip_addr', models.CharField(max_length=16, null=True)),
                ('proc_id', models.CharField(max_length=20, null=True)),
                ('proc_name', models.CharField(max_length=50, null=True)),
                ('is_hide', models.IntegerField(default=0, max_length=1, null=True)),
                ('time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Syscall',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('host_id', models.IntegerField(max_length=10, null=True)),
                ('host_name', models.CharField(max_length=30, null=True)),
                ('ip_addr', models.CharField(max_length=16, null=True)),
                ('syscall_id', models.IntegerField(max_length=10, null=True)),
                ('syscall_name', models.CharField(max_length=30, null=True)),
                ('re_sys_addr', models.CharField(max_length=30, null=True)),
                ('now_sys_addr', models.CharField(max_length=30, null=True)),
                ('is_edit', models.IntegerField(default=0, max_length=1)),
                ('time', models.DateTimeField(null=True)),
            ],
        ),
    ]
